name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - mater
    paths:
      - Pet-Home-Spring/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: pet
        ports:
          - 3307:3306
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      defaults:
        run:
          working-directory: ./Pet-Home-Spring

      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '8'
            cache: 'maven'
