name: CI - Build Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - Pet-Home-Spring/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: pet
        ports:
          - 3306:3306
        restart: unless-stopped
        healthcheck:
          test: "mysqladmin ping -h localhost -u root --password=1234"
          interval: 10s
          timeout: 5s
          retries: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: Pet-Home-Spring
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
      - name: Build and run Unit/Integration Tests with Maven
        run: |
          cd Pet-Home-Spring
          ./mvn clean verify