name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - mater
    paths:
      - Pet-Home-Spring/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: pet
        ports:
          - 3307:3306
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      defaults:
        run:
          working-directory: ./Pet-Home-Spring

      steps:
        - uses: actions/checkout@v3
        - name: Slack commit message and sha
          run: >
            curl -X POST -H 'Content-type: application/json'
            --data '{"text":":github: https://github.com/amigoscode/spring-boot-full-stack/commit/${{ github.sha }} - ${{ github.event.head_commit.message }}"}' 
            ${{ secrets.SLACK_WEBHOOK_URL }}
        - name: Send Slack Message
          run: >
            curl -X POST -H 'Content-type: application/json'
            --data '{"text":"Deployment started :progress_bar: :fingerscrossed:"}' 
            ${{ secrets.SLACK_WEBHOOK_URL }}
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '8'
            cache: 'maven'
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        - name: Set build number
          id: build-number
          run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
        - name: Send Slack Message
          run: >
            curl -X POST -H 'Content-type: application/json' 
            --data '{"text":":maven: Building with Maven"}' 
            ${{ secrets.SLACK_WEBHOOK_URL }}
        - name: Build Package Push with Maven
          run: mvn -ntp -B verify -Ddocker.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build

        
